name: ergonomic_office_chair_manager
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter_bluetooth_serial: ^0.4.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  meta: ^1.8.0
  get_it: ^7.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_stateful_bloc: ^0.1.0-beta

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
